import type { Metadata } from 'next'
import './globals.scss'

export const metadata: Metadata = {
  title: 'framer motion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru-Ru">
      <body>{children}</body>
    </html>
  )
}
