import type { Metadata } from 'next'
import './globals.scss'
import styles from './layout.module.scss'
import cn from 'classnames'

export const metadata: Metadata = {
  title: 'framer motion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const line: string[] = [
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
    "circle",
    "x-shape",
  ]
  const lines: string[] = [
    'line1',
    'line2',
    'line3',
    'line4',
  ]

  return (
    <html lang="ru-Ru">
      <body>
        <div className={styles.lines}>
          {lines.map((_, index) => {
            return <div key={index} className={styles.line}>
              {line.map((shape, index) => {
                return <div key={index} className={cn({
                  [styles.shape]: shape === 'circle',
                  [styles.x_shape]: shape === 'x-shape'
                })}>
                </div>
              })}
            </div>
          })}
        </div>
        {children}
      </body>
    </html>
  )
}
